- name: "Push suricata repo"
  synchronize:
    src: dtag_suricata
    dest: /tmp/

- name: "Build image"
  become: True
  docker_image: 
    name: suricata
    force: True
    path: /tmp/dtag_suricata

- name: "run suricata"
  become: True
  docker_container:
    state: started
    name: suricata
    image: suricata
    volumes:
      - /var/log/suricata
    network_mode: host
    privileged: True

- name: "create eve.json"
  become: True
  command: docker exec suricata bash -c "touch /var/log/suricata/eve.json; chmod 666 /var/log/suricata/eve.json"

- name: "restart suricata"
  become: True
  docker_container:
    state: started
    name: suricata
    restart: True
    volumes:
      - /var/log/suricata
    image: suricata
    privileged: True
    network_mode: host

- name: "start sending logs to SOC"
  become: True
  command: docker exec suricata bash -c "tail -f var/log/suricata.eve.json | nc -w 1 -u {{syslog_server}} 514"
  when: syslog_server is defined
